version: '3.8'

services:
  postgres-db:
    image: postgres
    restart: always
    ports:
    - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms-email
    volumes:
    - ./postgres-data:/var/lib/postgresql/data




